# config file containing simulation parameters

debug-flag: True
plot-flag: True
repeat: 1

# general
num-players: 7
schedule-length: 164
start-date: '23/01/2020'
demand-file: './data/covid_allDemand.csv'
storage-file: './config/storage_details.csv'
additional-storage: 50.0
output-dir: './results/'
output-name: '23_january_test/'
forecast-error: 0.2
players:
  0: 'east'
  1: 'london'
  2: 'midlands'
  3: 'north_east'
  4: 'north_west'
  5: 'south_east'
  6: 'south_west'

# pricing
# 0,3 is for the storage,
# 1,2 are for the general quadratic pricing
pricing-coeff:
  0: 50000.0
  1: 0.01
  2: 0.000008
  3: 0.000001

# iteration
max-time: 1300
max-iter-game: 20
max-iter-opt: 1000
eps: 3

