# config file containing all(!) simulation parameters

debug-flag: True

# general
num-players: 7
schedule-length: 10
start-date: '23/03/2020'
demand-file: './data/covid_allDemand.csv'
forecast-error: 0.7


# pricing
pricing-coeff:
  0: 0.0
  1: 1.0
  2: 1.0


# storage
storage-rate: 1000000
usage-rate: -1000000
initial-state: 0
max-capacity: 10000000000
min-capacity: 0


# iteration
max-time: 1300
max-iter: 10000
eps: 100

