# config file containing all(!) simulation parameters

# general
num-players: 7
schedule-length: 280
start-date: '23/03/2020'
output-dir: './results/'
demand: './data/covid_allDemand.csv'


# pricing
pricing-coeff:
  0: 0.0
  1: 1.0
  2: 1.0


# storage
charge-rate: 1000000
discharge-rate: -1000000
initial-soc: 0
max-capacity: 10000000000
min-capacity: 0

