# config file containing all(!) simulation parameters

# general
num-players: 7
schedule-length: 280
start-date: '23/03/2020'
output-dir: './results/'
demand-file: './data/covid_allDemand.csv'
debug-flag: False


# pricing
pricing-coeff:
  0: 0.0
  1: 1.0
  2: 1.0


# storage
storage-rate: 1000000
usage-rate: -1000000
initial-state: 0
max-capacity: 10000000000
min-capacity: 0

